### ISSUE TITLE
Inbox and comments

### ISSUE THREAD

**Issue by scratchyone** [halcyonnouveau/roux.rs#8]
I'm worried that the inbox and comments structs aren't 100% accurate. Do you know of a good source to verify these? I've fixed most of the issues, but it seems like the only good way to test these is just to leave them running looking at new comments and see if they throw an error

**Comment by beanpuppy** [comment]
Yeah I haven't been able to find a good source either. The [docs](https://github.com/reddit-archive/reddit/wiki/JSON) are out of date and don't provide everything.

I've mainly just been looking at other wrappers and seeing what they implement. The Python wrapper PRAW is well documented, so you may want to look at their [comment.py](https://github.com/praw-dev/praw/blob/master/praw/models/reddit/comment.py) file.

**Comment by scratchyone** [comment]
Thank you! I’ll read through that. I’m also going to try improving the error messages so it’s easier to see exactly what’s wrong with the structs

**Comment by scratchyone** [comment]
Ok this is rather strange, the kind field doesn't always exist

**Comment by beanpuppy** [comment]
Yep, lot's of fields don't seem to always appear. It would have been nice of them to tell us which ones they are, but the past few years seems to indicate that Reddit wants to be more of a walled-off garden so we're left with this "less than stellar" API.

But I'm going to close this issue now as I don't think further discussion is needed. If you have more to add, feel free to re open it.
