### ISSUE TITLE
get_feed after?

### ISSUE THREAD

**Issue by dorind** [halcyonnouveau/roux.rs#9]
currently there's no way of retrieving data in chunks, for example fetch the first 25 posts and at some point later retrieve another, say 25 posts, the get_feed function has a `limit` arg,  however it's lacking an `after` arg, do you intend on adding it?

**Comment by beanpuppy** [comment]
I was actually unaware that was a thing. But after [reading](https://www.reddit.com/r/redditdev/comments/2uymft/help_please_re_after_and_before_in_api/) about it, it seems simple to implement.

I'll try add it in soon.

**Comment by beanpuppy** [comment]
Added in b5b044b65bca7665ad863a85f6ab0dd5f45bd9c1.

**Comment by dorind** [comment]
thank you!
